TagTree         <- ElementLine* Element?
ElementLine     <- Element EOL
Element         <- (TagList / Value+ / Spacing)
TagList         <- Tag (TAGSEP Spacing TagList?)?
Tag             <- TagName Value* Attribute* Nested?

Nested          <- Spacing '{'  ElementLine* Spacing '}' Spacing

TagName         <- Spacing (Namespace ':')? Identifier Spacing
Namespace       <- Identifier

Attribute       <- Key '=' Value

Key             <- Spacing (Namespace ':')? Identifier Spacing

Value           <- Spacing (StringEscaped / StringRaw / Date / Time / Number / Boolean / Null / Binary) Spacing

StringEscaped   <-  '"' < ( '\\' . / !'"' . )* > '"'
StringRaw       <-  '`' < (! '`' . )* > '`'
Number          <-  Decimal / Float32 / Float64  / Int64 / Int32
Int32           <- < [0-9]+ >
Int64           <- < [0-9]+ > [Ll]
Float32         <- < [0-9]+ '.' [0-9]+ > 'f'
Float64         <- < [0-9]+ '.' [0-9]+ > 'd'?
Decimal         <- < [0-9]+ '.' [0-9]+ > 'BD'
Boolean         <- 'true' / 'false' / 'on' / 'off'
Null            <- 'null'
Date            <- < '-'? [0-9]{4} '/' [0-9]{2} '/' [0-9]{2} >
Time            <- < '-'? ([0-9]+'d' ':')? ([0-9]{2} ':')+ [0-9]{2} ('.' [0-9]{3} ('-' TimeZone)? )? >
TimeZone        <- < [a-zA-Z0-9/_:+-]+ >
# base 64 encoded
Binary          <- '[' < [A-Za-z0-9+/=]* > ']'

Identifier      <- < [a-zA-Z_] [a-zA-Z0-9_.$-]* >

Comment         <- BlockComment / LineComment

LineComment     <- ("//" / "--" / "#") (!EOL !EOF .)*
BlockComment    <- "/*" < (!"*/" .)* > "*/"

LineCont        <- '\\' '\n'

Spacing         <- < ( WS / Comment / LineCont )* >
TAGSEP          <- ';'
WS              <- [ \t]+

EOL             <- '\n' / '\r\n' / '\r'
EOF             <- !.
